name: HakuaPay
main: jp.hakuaserver.hakuapay.HakuaPay
version: 1.0
api-version: 1.21
depend: [Vault, Citizens]
commands:
  money:
    description: プレイヤーの残高を表示します。
  pay:
    description: 他のプレイヤーにお金を送ります。
    usage: /pay <player> <amount>
  setmoney:
    description: プレイヤーの残高を設定します。
    usage: /setmoney <player> <amount>
    permission: hakuapay.admin
  job:
    description: プレイヤーの職業を設定します。
    usage: /job <player> <job>
    permission: hakuapay.command.job
  jobmob:
    description: プレイヤーモブを生成します。
    usage: /jobmob <名前> <スキン名>
  removenpc:
    description: NPCを削除します。
    usage: /removenpc <NPC名>
    permission: hakuapay.admin
  checkjob:
    description: プレイヤーの現在の職業を確認します。
    usage: /checkjob <player>
    permission: hakuapay.checkjob
  addjob:
    description: 新しい職業を追加します。
    usage: /addjob <職業名>
    permission: hakuapay.admin
  editjob:
    description: 職業のアクションを編集します。
    usage: /editjob <職業名> <アクション> <対象> <報酬>
    permission: hakuapay.admin
  addmoney:
    description: プレイヤーの所持金を追加します。
    usage: /addmoney <player> <amount>
    permission: hakuapay.admin

permissions:
    hakuapay.admin:
        description: 管理者権限
        default: op
    hakuapay.user:
        description: ユーザー権限
        default: true
    hakuapay.command.money:
        description: 残高確認コマンドの実行を許可します。
        default: true
    hakuapay.command.pay:
        description: お金を送るコマンドの実行を許可します。
        default: true
    hakuapay.command.job:
        description: 職業を設定するコマンドの実行を許可します。
        default: true
    hakuapay.checkjob:
      description: 職業確認コマンドを実行する権限
      default: true